Repository govhackaustralia/hackerspace3, pull requests merged in 2021-07, with the labels that each got.

#283 Add turbolinks:before-cache to prevent duplicate table initialisations
  app/assets/javascripts/application.js
Labels: bug, clean code, enhancement

#288 Rearrange Region Names in Account and Profile Forms
  app/views/accounts/edit.erb
  app/views/users/_full_form.html.erb
Labels: enhancement

#289 Add Eligibility Requirements to All Challenge Panels
  app/views/challenges/_challenge_panel.erb
Labels: enhancement

#280 Update User in Mailchimp List
  Gemfile
  Gemfile.lock
  README.md
  app/jobs/mailchimp_update_job.rb
  app/models/user.rb
  test/jobs/mailchimp_update_job_test.rb
Labels: enhancement

#290 Create EmploymentStatus model to enable multiple employment options
  app/controllers/demographics_controller.rb
  app/models/employment_status.rb
  app/models/profile.rb
  app/services/demographics_report.rb
  app/views/demographics/edit.erb
  config/locales/en.yml
  db/migrate/20210717002651_create_employment_statuses.rb
  db/schema.rb
  db/seeders/user_seeder.rb
  test/controllers/demographics_controller_test.rb
  test/fixtures/employment_statuses.yml
  test/models/employment_status_test.rb
  test/models/profile_test.rb
Labels: enhancement

#296 Make 2020 Stuff only Visible for Competition 2020
  app/views/competitions/show.html.erb
  app/views/resources/index.erb
Labels: clean code

#291 Event > Registrations UI update
  .gitignore
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/csv_button.scss
  app/assets/stylesheets/components/event_info.scss
  app/assets/stylesheets/components/event_tile.scss
  app/assets/stylesheets/components/tiles.scss
  app/assets/stylesheets/layouts/event_index.scss
  app/assets/stylesheets/layouts/event_page.scss
  app/assets/stylesheets/layouts/register.scss
  app/views/events/_event_collection.html.erb
  app/views/events/_event_map_video.html.erb
  app/views/events/_event_registration_team_links.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/registrations/_agree_to_code_of_conduct.html.erb
  app/views/registrations/edit.html.erb
  app/views/registrations/new.html.erb
  app/views/registrations/show.html.erb
Labels: enhancement

#301 Redo Sponsorship Position
  app/controllers/admin/regions/events_controller.rb
  app/controllers/admin/sponsorship_types_controller.rb
  app/controllers/events_controller.rb
  app/models/sponsorship_type.rb
  app/views/admin/sponsorship_types/_form.html.erb
  app/views/admin/sponsorship_types/index.html.erb
  db/migrate/20210724052650_rename_sponsorship_type_order.rb
  db/schema.rb
  db/seeders/competition_seeder.rb
  test/controllers/admin/sponsorship_types_controller_test.rb
  test/fixtures/sponsorship_types.yml
  test/models/sponsorship_type_test.rb
Labels: bug, clean code

#302 Move Resources YAML Records to DB
  app/controllers/resources_controller.rb
  app/models/competition.rb
  app/models/concerns/position.rb
  app/models/resource.rb
  app/models/sponsorship_type.rb
  app/views/resources/data_portals.erb
  app/views/resources/index.erb
  app/views/resources/tech.erb
  db/migrate/20210724100750_create_resources.rb
  db/schema.rb
  db/seeders/competition_seeder.rb
  test/fixtures/resources.yml
  test/models/competition_test.rb
  test/models/resource_test.rb
  test/models/sponsorship_type_test.rb
Labels: enhancement
